version: "1"
rules:
  - base: dev
    upstream: space-wizards:master    # change `wei` to the owner of upstream repo
    mergeMethod: merge
    conflictReviewers:      # Optional, on merge conflict assign a reviewer
      - MWGMorningwood
